# Configuration file

bitstreams:
  oscillo_url: https://github.com/Koheron/zynq-sdk/releases/download/v0.1-beta.6/oscillo.bit
  spectrum_url: https://github.com/Koheron/zynq-sdk/releases/download/v0.1-beta.6/spectrum.bit
