# Configuration file

bitstreams:
  oscillo_url: https://github.com/Koheron/zynq-sdk/releases/download/v0.1.2/oscillo.bit
  spectrum_url: https://github.com/Koheron/zynq-sdk/releases/download/v0.1.2/spectrum.bit
